- README.md
- start.sh
Instead of creating a directory in home, I've changed the script to save it as a tmp file and deletes it from your system once you are done with it.
I've also changed it to use sh instead of bash, because it runs a bit faster (provided you have linked /bin/sh to dash or something similar, instead of bash).
The startup command is changed to pipe the curl output into sh instead because it's a bit cleaner.
> Save binary as a tmp file

- src/commands/system-update.sh
If for some reason after the /etc/os-release the DTYPE variable is still unknown the rate-mirrors command will fail
I did a local dtype variable for this to don't change the global DTYPE to arch
> default dtype to arch when it is unknown for rate-mirrors

- src/commands/common-script.sh
- src/commands/dotfiles/alacritty-setup.sh
- src/commands/dotfiles/kitty-setup.sh
- src/commands/dotfiles/rofi-setup.sh
- src/commands/system-setup/1-compile-setup.sh
- src/commands/system-setup/2-gaming-setup.sh
- src/commands/system-update.sh
- start.sh
- startdev.sh
Use the `-e` option when using the `echo` command, as backslashes are not interpreted by default.  This causes `echo` to print color escape codes as-is.  This PR also replaces existing `printf` calls with `echo` for consistency.
> Fix colors with echo commands

- src/commands/system-update.sh
- Changed to use zypper dup, because that's the way to update openSUSE Tumbleweed and Slowroll installs
> Changed zypper update

- README.md
This the the current one-liner:
```bash
curl -fsSL https://github.com/ChrisTitusTech/linutil/releases/latest/download/start.sh | sh
```
But this one looks better :D
```bash
bash <(wget -qO- https://christitus.com/linux)
```
I know the URL does not point to the script yet, but would be awesome to see this one go live!
closes #22
> minor: shorter oneliner

- .github/workflows/linutil.yml
- .github/workflows/rust.yml
I added `cargo fmt --all --check`, `cargo clippy` and changed `actions-rs/toolchain` to `dtolnay/rust-toolchain` because [actions-rs/toolchain](https://github.com/actions-rs/toolchain) is no longer maintained.
[Rust FMT](https://github.com/rust-lang/rustfmt) is a tool for correctly formatting Rust code and [clippy](https://github.com/rust-lang/rust-clippy) is a lint-checker for improving Rust code ([docs](https://doc.rust-lang.org/clippy))
> CI: Add lint checks & change actions-rs/toolchain to dtolnay/rust-toolchain

- src/commands/system-setup/1-compile-setup.sh
It still had the old repo name and had to be changed so the clone worked as expected.
> Change linux-setup to linutil in 1-compile-setup.sh, closing #50

- start.sh
* fix shellcheck warnings
* rename variables to be consistent
* use printf instead of echo (printf is a shell builtin)
i'd like to add that `local` is a bashism, and won't run on POSIX shells like dash. i've opted to just use `unset` after the function does its check, which works fine in this scenario. if not, you can also just change the shebang to `#!/usr/bin/env bash`.
the shellcheck warnings that were fixed can be found here:
* https://www.shellcheck.net/wiki/SC3037
* https://www.shellcheck.net/wiki/SC3043
* https://www.shellcheck.net/wiki/SC2086
> very minor init script changes

- .github/workflows/linutil.yml
- .github/workflows/pre-release.yaml
Statically link linutil binary against musl libc 
Modify GitHub workflows to build the linutil binary against the x86_64-unknown-linux-musl target. This leads to the binary being statically linked against the musl libc, removing the glibc dependency. This will improve compatibility on distros which include a different libc or a build of glibc which isn't supported by rust's x86_64-unknown-linux-gnu target in the current toolchain version. 
The TUI successfully builds against the musl target, and successfully launches.
The size of the binary increases by a small amount (~100KB) due to static linking. The performance impact should be negligible.
- Resolves #37
Other changes to the workflow files are from format on save
> chore: Build linutil against musl libc

- src/commands/security/firewall-baselines.sh
- src/list.rs
Added a security Folder with a basic firewall feature.
Hello, once again, I added a new feature called Security.
This folder is meant to do any tasks like hardening or managing security of a linux  machine.
I have added a template firewall rules feature.
It just runs your recommended firewall rules with UFW. [CTT 3 Security Mistakes](https://christitus.com/linux-security-mistakes/)
I have tested this on Kubuntu 24.04 with linutil, and it works fine.
This could make users easily automate security processes.
None
Maybe change the rules or added extra options for the user to choose.
> Added Security Folder

- src/commands/system-setup/1-compile-setup.sh
Hello, this is my first contribution, I was using your script and saw that when using
the Build Prerequisites feature, APT was not finding the packages on my kubuntu install.
It would spit out a error saying that the packages were not found (even though they exist). I found out that it was because of a formatting issue on $DEPENDICIES.
The way I fixed this was I removed the quotes around the $DEPENDENCIES variable
which made the package manager (apt) detect them. I also added a optional fix where
instead of just detecting "apt" it also detects apt-get and nala and executes the main
install function.
Lastly I also added the same patch to the other package manager function. 
I did these changes to make apt detect the packages so it could install them.
I have tested it on my kubuntu 24.04 …
> fixed pkg manager checks

- .github/workflows/linutil.yml
- .github/workflows/pre-release.yaml
- start.sh
- startdev.sh
Build aarch64 binaries
Build aarch64 binaries using cross-rs, which allows for automated cross compilation using docker images. Update start.sh and startdev.sh to link to them. 
I locally tested the build command, along with the start scripts to ensure they reach the correct URLs.
Note that releases without aarch64 binaries will throw an error on download for users on aarch64 systems, but they aren't able to launch the current x86_64 binaries regardless.
> feat: Build aarch64 binaries

- .github/workflows/rust.yml
Remove cargo check workflow
`cargo clippy` runs an instance of `cargo check` by default (https://github.com/rust-lang/rust-clippy/blob/master/src/main.rs#L62). There is no need for an extra workflow to run cargo check on the side. Issues which `cargo check` will flag will also be caught by clippy.
> chore: Remove duplicate cargo check workflow

- src/list.rs
Refactor key handling match statement. No changes to functionality.
Remove unnecessary identical early returns. Move if statement in enter key handling into the match case to remove unnecessary else clause which returns the same as the default case.
No changes to logic.
Code is slightly more readable.
> refactor: Small improvements to formatting of key handling

- src/main.rs
Fix search, / and q acting as char
Before, when searching, pressing the letter q would quit the programme.
Same goes for / using its action rather than acting a letter.
Following this, both act as letters. To exit the program, the user must get out of the search before with <ENTER> or <ESC>.
Also did a bit of refactoring to reduce the amount of if. This would go out  of hands when adding new commands ( I am about to... :D ).
Manual testing
Can now write words containing q and / :) 
Don't look at the long list of commits, this is me walking on the bug while adding a new feature. Had to branch out and go back to fix it independently.
> Fix search commands

- src/commands/system-setup/4-remove-snaps.sh
- src/list.rs
Added an option to remove snaps and snapd from the system. 
On Ubuntu, this script will also put a hold on snapd to prevent it from being reinstalled.
- New feature
added script `src/commands/system-setup/4-remove-snaps.sh`
added node in `src/list.rs` so that the new script can be run.
I installed various distributions via distrobox, installed snapd, then removed snapd with this new script, and checked that /var/lib/snapd/ was no longer present to indicate that snapd was removed successfully. On ubuntu, I also checked that `sudo apt install firefox` would not install snapd.
New option under system-setup
This PR is a step towards resolving issue #35
Option to install apt or flatpak version of Firefox and other packages on Ubuntu should likely be added in the future, because this script …
> Added option to remove snaps

- src/main.rs
- src/state.rs
- src/theme.rs
Refactor Theme
Allow to add/remove theme while avoiding to index out of bounds. 
Plus add the ability to change them at runtime by cycling. Press t to go forward and T to go backward. 
Also, themes are now self documenting in the help section.
Manual test only
Low impact.
> Refactoring : Easily add theme and cycle through

- src/commands/system-setup/arch/server-setup.sh
Adding SE keymap.
Adding Swedish (se) keymap to Arch server install script
Added Swedish language to the keymap list, lot of languages are in the list but missing Swedish.
Tested the script independendly, works fine on my end.
No difference, it's giving more options to the user.
-
-
> Adding Swedish keymap to Arch server install script

- src/state.rs
- src/theme.rs
Refactor next & previous theme to modify the value in place
Currently, theme next() and prev() methods return a new value. There's no purpose for this, since we're only using the next and prev methods for modifying the value of the theme variable itself. Instead, I've changed the functions to modify the receiver in place, which improves the readability of the code.
Next and previous theme function correctly.
> refactor: Modify theme in place

- src/floating_text.rs
Add word wrap to preview window
Currently, if a line in the preview window exceeds its width, it is not possible to view the rest of the line. The preview window cannot be scrolled horizontally, and text outside of the window will not be rendered. This PR proposes implementing word wrap for the preview window, by splitting each line into chunks of the floating window's width. 
Preview window scrolling functions correctly, and all lines are rendered properly.
Improve user understanding of scripts, solve potential security concerns from unreadable code.
> feat: Add word wrap to preview window

- Cargo.toml
- build.rs
- src/state.rs
Provide the date of the linutil build to the user
This provides the same feature #210 claims to be trying to implement. However, this actually works, rather than being completely broken LLM-generated code that doesn't work whatsoever and would block the drawing thread every single time even if it did build.
The build date is correctly displayed.
- Closes #210
> feat: Display build date to user, rather than current date

- build.rs
Re-populate build_date variable whenever any code is modified
#221 added a date variable to be filled by the build script, but the build script only specifies that it's re-run whenever a file in the src/commands directory (a script) is modified. If changes occur to the code but not to a script, build.rs will not repopulate the date field and the previous date will remain.
The compile_time crate appears to have the same issue, from my testing. Therefore, I propose instead modifying the build script to re-run whenever any code (in the src/ directory) is modified. As long as no major additions are made to build.rs, this will have no sizable impact on compile time since the build script only includes a few print statements and a check for the date.
Modifying the system clock and then editing …
> fix: Recheck date whenever code is modified

- Cargo.toml
Optimise for weight at the expense of compile time, speed and we strip debuging elements
Reduce binary weight to reduce waiting time for slower connection.
Indicate to the compiler to : 
- Optimise for weight rather than speed
- Take more time to improve linking at compile time
- Remove debug info (is already the default on release)
- Compile using only 1 code gen unit (longer compile time in exchange for better optimisation)
- To abort when under panic (reduce code generation, and so far the unwinding with Ratatui is horrible)
- Strip any symbols from the binary. (An other option is strip = "debuginfo" if we don't want to go that far)
- Incremental build turned to off (in our case this should not have any effect, but there is cases where loses of  performance where noted)
Yes
Reduce the …
> Reduce the weight of the produced binary for faster start time

- src/running_command.rs
Send ASCII DEL character to PTY on backspace, rather than ASCII BS
ASCII BS (0x08) is not the character sent by terminal emulators for the backspace key. Rather, ASCII DEL (0x7f) is. This change fixes unexpected behaviour from certain programs which perform different actions for these 2 inputs, such as `sudo`.  
`sudo` behaves correctly on backspace, keycode sent to pty matches that sent to host terminal.
- Resolves #231 
- Resolves #230
> fix: Use proper backspace character in PTY

- .gitignore
- src/float.rs
- src/floating_text.rs
- src/hint.rs
- src/main.rs
- src/running_command.rs
- src/state.rs
In this PR I made a bottom bar that displays the correct keyboard shortcuts depending on the context.
I also added a credits label in the top left corner.
>[!Note]
> 
>  This pr did not do much refactoring and does not change how this app works on a deeper level.
This should be ready to merge.
> Create a dynamic hotkey list

- tabs/applications-setup/dwmtitus-setup.sh
[Dwm-Titus-Setup] add slstatus installation option
This PR introduces a new function to optionally install `slstatus` during the DWM setup process. It prompts the user for confirmation and handles different responses (yes/no). Additionally, it ensures proper directory navigation and error handling during the installation process using the system's escalation tool. This change enhances the flexibility of the DWM setup script by allowing users to choose whether or not to install `slstatus`.
- Resolves #351 
Provide any suggestion if required changes.
> [Dwm-Titus-Setup] add slstatus installation option

- tui/src/float.rs
- tui/src/main.rs
- tui/src/state.rs
Added the ability to exit the application with Control-C to match the expected behavior of some users
Added a screen blank on exit to prevent text present on screen from persisting from before starting the application.
Control-C is the universal "I want to get out of here" chord. Having the binding only exist on the 'q' key makes it unintuitive to exit the app while running. It was only a few lines that needed to be added to accomplish this.
Also, I noticed that stale text would be persisted from before starting the application, so I removed the cursor position reset and it seems to be fixed.
I verified that both 'q' and Control-c behave as expected, and I ran a test neovim install to verify that package management functionality wasn't broken.
I believe that this makes the application …
> Close linutil on Control-C, don't reset cursor position on exit

- .github/workflows/pr-labels.yaml
> [!WARNING]  
> On Repo Settings go to Actions - General then make sure Workflow permissions is set to Read and write permissions.
Copy of: [2749](https://github.com/ChrisTitusTech/winutil/pull/2749) (from winutil)
- automatically adds/removes labels to PR's based on body using template components. 
- if label does not exist yet, it will add it so no need for additional config outside of the workflow
- Labels will be automatically applied/removed from PR's based on checking following checkboxes:
```
```
- Tested on own repo, worked with adding and removing labels. [mwm](https://github.com/MyDrift-user/mwm/pull/1)
- Chris does not need to manually label the PRs anymore, it lies in the hands of the OP to correctly label the PR.
> [CI Workflow] PR auto label MGMT

- tabs/applications-setup/mybash-setup.sh
- tabs/applications-setup/neovim-setup.sh
- tabs/applications-setup/tab_data.toml
~~There is 1 issue with how the cloned dir is being handled; if the folder already exists then it won't work correctly, this can be solved by adding a check to see if that path already exists and to delete it if it does. I did not know if you wanted that functionality or not so I left it out.~~ Solved with [55c6db1](https://github.com/ChrisTitusTech/linutil/pull/335/commits/55c6db1b1296025189fea4ae44cfa913b5c7e2f8)
This PR includes refactoring of the setup scripts in the original repositories to follow Posix compliant standards, I rechecked both files using the checkbashisms package to make sure.
More error handling could be added to the nvim-setup script; I have decided to refrain from doing that for now, If you do want more error handling I can make a PR tomorrow.
- About the package …
> Move mybash and CTT nvim to Linutil with minor refactoring

- tabs/applications-setup/fastfetch-setup.sh
- tabs/applications-setup/tab_data.toml
Works as expected.
- Resolves #400
> Add fastfetch

- tabs/applications-setup/dwmtitus-setup.sh
Correctly Detect Pictures Directory and Clone Path for Background
The `configure_background` function couldn't correctly detect existing `Pictures` directory and installed the `nord-background` repo to the top level of the `Pictures` directory
https://github.com/ChrisTitusTech/linutil/issues/303
Tested both having no `Pictures` directory and an existing `Pictures` directory, then ran the `DWM-Titus` script from the TUI. Both times the images from the `nord-background` repository wound up in `~/Pictures/background`
N/A
- Resolves #303 
This will still fail if you already have a `~/Pictures/nord-background` folder that's not empty but that seemed a bit extra to go clobbering that if it existed.
> fix: Correctly Detect Pictures Directory and Clone Path for Background

- startdev.sh
> Replace remaining echo -e statement

- tabs/utils/wifi-control.sh
Simple bug-fix, before the wifi-manager was not requesting credentials; now it does, and now you can successfully connect to any internet connection, I've also fixed the issues with duplicate entries & empty entries when selecting a wifi to connect to.
In this fix I used a temp-file like in the other rewritten util scripts to store the contents of the grabbed wifi-names locally and then remove that file after use; this is a posix compliant approach to bash arrays and unfortunately I do not know any alternatives to storing temp-files, this can be refactored further in the future.
I've also removed the remaining read -s bashisms in this script that weren't removed prior.
Replaced / removed some redundant code as well.
After fixing:
Invalid choice:
Before entry fix:
Before wifi connecting …
> Fix wifi-manager

- core/src/inner.rs
- core/src/lib.rs
- tabs/applications-setup/tab_data.toml
- tabs/gaming/tab_data.toml
- tabs/security/tab_data.toml
- tabs/system-setup/tab_data.toml
- tabs/utils/tab_data.toml
- tui/src/float.rs
- tui/src/floating_text.rs
- tui/src/hint.rs
- tui/src/state.rs
Implement command description for commands just like how command preview works
Add command description be using **D** key just like how command preview works
Works as expected.
When new scripts are added a description must be added in the toml for command description to work
- Resolves #244
> feat: Command Description

- tabs/system-setup/system-cleanup.sh
- tabs/system-setup/tab_data.toml
This is a comprehensive system cleanup script that performs various cleanup tasks.
- Removes unused packages
- Common cleanup tasks (journalctl, temporary files, log truncation)
- Optional user cache and trash cleanup
This script provides a unified approach to system cleanup across different Linux distributions, improving system performance and freeing up disk space.
> System Cleanup

- tabs/utils/monitor-control/auto_detect_displays.sh
- tabs/utils/monitor-control/set_brightness.sh
- tabs/utils/monitor-control/set_resolutions.sh
- tabs/utils/monitor-control/utility_functions.sh
> Replace echos with printf (monitor-control)

- tabs/system-setup/fedora/configure-dnf.sh
- tabs/system-setup/fedora/multimedia-codecs.sh
- tabs/system-setup/fedora/rpm-fusion-setup.sh
- tabs/system-setup/tab_data.toml
Just some essential DNF changes to at least make it usable and faster by a margin.
Also added installation support for multimedia codecs
-  New feature
Checked on my System, it works
- Resolves #289
> Added DNF configuration and Multimedia Support for fedora and other Redhat Distros

- tabs/common-script.sh
Refactor command_exists function to use command -v instead of which
`command_exists` function uses `which`, that is not POSIX-compliant that may result in error in some systems. A simple refactor to `command -v` solves the issue. `command -v` is also a POSIX-compliant built-in command.
- Resolves #https://github.com/ChrisTitusTech/linutil/issues/211
> refactor: command_exists 

- core/Cargo.toml
Reduce the size of the `linutil` binary by removing unused features from `core/Cargo.toml`
```shell
ls -l target/release/linutil
-rwx------ 2 zdiff zdiff 1366216 Sep 12 18:48 target/release/linutil
```
```shell
ls -l target/release/linutil
-rwx------ 2 zdiff zdiff 1365368 Sep 12 18:50 target/release/linutil
```
Build and ran `linutil` using `cargo build --release && ./target/release/linutil`
Reduction in binary size
> Reduce the size of the linutil binary by removing unused features from `core/Cargo.toml`

- tabs/system-setup/system-update.sh
Rate mirrors heads up message
I've noticed that users often cancel the script while rate-mirrors is running, due to the lack of a visible message indicating that the process is ongoing. This results in an empty mirrorlist making it a hell for linux newbies. Adding a  heads-up message informing the user that the process may take a couple of seconds to complete can save the day for a linux rookie.
> enhancement: Rate mirrors heads up message

- .github/workflows/bashisms.yml
Modified `bashisms.yml` to only check modified `.sh` files using `git diff --name-only <base branch> HEAD tabs`.
Works like a charm :))
Less not deserverd CI failures i guess.
> Modify the bashisms workflow to only check modified files

- tabs/system-setup/1-compile-setup.sh
Removes the unnecessary functionality: "install_additional_dependencies" the packages that would get added to that can just be added to the function above it "installDepend" making this functionality unneeded
Also this functionality is really outdated as seen with the structure of it and it not relying on PACKAGER from common-script
> Remove redundant functionality

- tabs/applications-setup/browser-setup.sh
- tabs/applications-setup/tab_data.toml
- a script to install popular browsers(brave , chrome, chromium,firefox, vivaldi, lynx) for arch, debian, opensuse and fedora based distros
> added browser setup script

- tabs/system-setup/9-auto-mount.sh
- tabs/system-setup/tab_data.toml
- Automount disks script added.
> added auto mount script

- .github/workflows/linutil.yml
- I don't really know what type of change is this. I just added the aarch64 in CI and it works.
- Added aarch64 in workflow
- Tested on linutil fork and runs without errors.
- Resolves #450 
- Resolves #252 
- Resolves #259
- I took a look at the old errors of aarch64 build. I encounter similar errors when switching from my arch system to ubuntu20 testing system sometimes. Doing a cargo clean and re-building would resolve the errors. I am not sure whether these two issues are related. **For now aarch64 has no errors**. In case we encounter such errors in future we can fix them.
- The error happens when half of the cargo.lock gets build on newer glibc and the other half gets build on older glibc.
- `cargo clean` would clear all the old built crate binaries and will build again from the …
> Add aarch64 again

- tui/src/state.rs
Added lj's thought process from https://github.com/ChrisTitusTech/linutil/pull/490
- Separate the styles and title variables.
- Fixes the warning that pops up in terminal.
> refactor: Seperate style and title variables

- startdev.sh
- tabs/utils/ollama.sh
stupid bashisms invading again
tested and works
> Fix local vars bashisms that are not defined in posix

- .github/workflows/bashisms.yml
When a shell file is deleted or moved, this CI fails. This fixes it.
> Fixed the bashisms CI to only check files that exist

- core/tabs/applications-setup/office-suite-setup.sh
- core/tabs/applications-setup/tab_data.toml
added office suite setup script
> added office suite setup script

- .github/workflows/linutil.yml
- tui/Cargo.toml
- tui/src/state.rs
Crated a `tips` default feature. Tips only show when the feature is on.
Now this can be used with:
`cargo build --features tips`
`cargo build --no-default-features`
> Moved showing tips to a feature

- core/tabs/applications-setup/tab_data.toml
- core/tabs/utils/tab_data.toml
> Fixed alphabetical command sorting

- tui/Cargo.toml
- tui/src/state.rs
Move all logic relating to tips into the proper function, rather than leaving a hard to read line in the appstate constructor. Also make `rand` only a dependency when building the tips feature, since it's not used elsewhere.
> Refactor tips

- .github/workflows/rust.yml
- tui/src/state.rs
Changed the unnecessary `then` & `unwrap_or` to an if statement.
Modified the Rust workflow to fail if clippy returns warnings
> Fixed some Rust code structure and modified the workflow to fail if clippy returns warnings

- core/tabs/common-script.sh
Recently "CYAN" got added, so i implemented it into the common-script for more aesthetically pleasing visuals
tested
> Use more colors in common-script

- Cargo.lock
- tui/Cargo.toml
- tui/src/floating_text.rs
- tui/src/state.rs
Tree-sitter is a permissively-licensed, open-source parser framework, well known for its integrations in many popular editors (i use nvim, btw). Luckily, they provide Rust bindings that are reasonably straightforward to use. This PR implements syntax highlighting for the source preview, making it much easier to read for people wanting to understand the code behind commands that they are running.
- Implement tree-sitter-based syntax highlighting
Manual testing by perusing the previews of various commands
This should make it much easier to understand the source while being presented in the preview
> feat: implement syntax highlighting for preview text

- core/tabs/gaming/diablo-ii/d2r-loot-filters.sh
quotes vars to prevent globbing, adds colors, uses command_exists function defined in common-script
needs testing, though it should work fine. can't test because i don't own the game, but the first 18 lines work:
> Add colors to d2r-loot-filters

- tui/src/state.rs
#490 introduced a regression where entering an up directory (..) results in an empty command executing, instead of entering the parent directory. This resolves the issue by including a check for whether the current selection is an up directory in addition to whether it's a standard directory.
- Resolves #579
> fix: Correctly enter up directories

- README.md
- docs/index.md
---
Linutil is also available as a package in various repositories:
[![Packaging status](https://repology.org/badge/vertical-allrepos/linutil.svg)](https://repology.org/project/linutil/versions)
<details>
<summary>Arch Linux</summary>
Linutil can be installed on [Arch Linux](https://archlinux.org) with three different [AUR](https://aur.archlinux.org) packages:
- `linutil` - Stable release compiled from source
- `linutil-bin` - Stable release pre-compiled
- `linutil-git` - Compiled from the last commit (not recommended)
by running:
```bash
git clone https://aur.archlinux.org/<package>.git
cd linutil
makepkg -si
```
Replace `<package>` with your preferred package.
If you use [yay](https://github.com/Jguer/yay), [paru](https://github.com/Morganamilo/paru) or any other [AUR …
> Add package installation instructions to the docs and README

- tui/src/state.rs
- Fixed a bug that caused panic if the terminal size is smaller than the text length of warning message. 
- Works as expected no panics.
> fix: Min-term panic

- core/tabs/system-setup/fedora/rpm-fusion-setup.sh
Is there any reason for the rpm fusion setup not enabling the repos?
I was working on the Nvidia-driver script (on a non-standard fedora install)  and noticed that it was failing cuz rpm-fussion never got enabled globally and the rpm-fusion-nvidia repo only exists on fedora DE spins
> Enable RPMFusion repos as well on rpmfusion script

- core/tabs/applications-setup/Developer-tools/githubdesktop-setup.sh
- core/tabs/applications-setup/Developer-tools/neovim-setup.sh
- core/tabs/applications-setup/Developer-tools/ngrok-setup.sh
- core/tabs/applications-setup/Developer-tools/sublime-setup.sh
- core/tabs/applications-setup/Developer-tools/vscode-setup.sh
- core/tabs/applications-setup/Developer-tools/vscodium-setup.sh
- core/tabs/applications-setup/android-debloat.sh
- core/tabs/applications-setup/browser-setup.sh
- core/tabs/applications-setup/communication-apps/jitsi-setup.sh
- core/tabs/applications-setup/communication-apps/signal-setup.sh
- core/tabs/applications-setup/communication-apps/telegram-setup.sh
- core/tabs/applications-setup/communication-apps/thunderbird-setup.sh
- core/tabs/applications-setup/mybash-setup.sh
- core/tabs/applications-setup/office-suite-setup.sh
- core/tabs/utils/power-profile.sh
- Various package manager fixes.
> refact, fix: Package managers

- core/tabs/system-setup/gaming-setup.sh
I've edited the regex for checking presence of multilib package mirrors in `/etc/pacman.conf`.
> fix: multilib check in gaming setup

- core/tabs/applications-setup/linutil-installer.sh
The script tries to install `rustup`, but Debian doesn't provide it in stable repos. That's why the installation failed on Chris' latest stream.
> fix: Crates.io package installation on Debian & Fedora

- core/tabs/utils/auto-login.sh
A LOT of bugs here. Someone (@guruswarupa) didn't test this.
- Resolves #654
> Fix AutoLogin `printf` and `>` issues

- core/tabs/common-script.sh
the checkCommandRequirements function under checkEnv function in common-script.sh hard-depended on sudo, although doas could be picked as an $ESCALATION_TOOL.
I activated acouple of the scripts from with the UI, there was no error for not having sudo on my sudo-less system anymore.
Allows doas to properly be used as an escalation tool now.
- Similar to #193 which introduced doas support.
> fix: do not hard depend on sudo being installed

- tui/src/float.rs
- tui/src/floating_text.rs
- tui/src/hint.rs
- tui/src/running_command.rs
- tui/src/state.rs
Makes shortcut list dynamically sized
- Resolves #653
> implement dynamic shortcut list sizing

- core/tabs/utils/power-profile.sh
Auto power profiling in arch needs to run an extra command. added it to ensure all systems run it before setting power profile.
> Auto power profiling in arch needs to run an extra command.

- tui/src/state.rs
- Fixed a bug where floating window appears even though no command is selected.
- Working as expected.
> Fix: Selected-cmd bug

- core/tabs/applications-setup/Developer-tools/neovim-setup.sh
as suggested by Chris, we should use the appimage instead for debian so the installation goes through smoothly. Though he did say he would do it, i got bored and decided i would do it instead
tested
> Use the neovim app image for debian 12

- core/src/inner.rs
- core/src/lib.rs
- tui/src/confirmation.rs
- tui/src/float.rs
- tui/src/main.rs
- tui/src/state.rs
Having an accidental keypress result in a significant environment change sucks. Adding a prompt to confirm the execution of a command makes it less likely that a user will have a destructive command accidentally execute and have to decipher the command source to revert the changes (if they even are revertible).
locally, tested aborting and confirming command selections
should prevent accidental neovim config deletions, at least :)
- Resolves #686
> Feat: confirmation prompts

- core/tabs/system-setup/system-update.sh
Fixed nala update error, when executing the systemupdate on debian based systems with nala becouse of -y after the update, since nala update doesn't need -y.
edited the script under core/tabs/system-setup/system-update.sh
saved the changes
cargo run > Full System Update
Everything works without the error
fix for a typo/bug
- [ x I have performed a self-review of my own code.
> Fixed nala update error

- Cargo.toml
- tui/Cargo.toml
The updated version is already up on `crates.io`.
Ref https://github.com/ChrisTitusTech/linutil/issues/691#issuecomment-2381011204
No dep conflicts, everything updated, should work.
- Resolves #691
> fix(meta): bump crates versions to `24.9.28`

- core/tabs/system-setup/tab_data.toml
I added a description to the Full System Cleanup command in the System Setup section.
I built and ran the application, ensuring the description displayed as intended.
Descriptions are now available for commands that previously did not include them, which adds more context to inexperienced users.
- Improves the UI and the UX
> Add description to the System Setup section

- core/tabs/utils/auto-mount.sh
- `blkid` requires escalation to retrieve information.
- Tested on arch linux, working fine.
- Resolves #684
> fix: uuid retrieve bug

- .github/workflows/bashisms.yml
Yeah so changed a bit here.
1. Does not use GitHub Output to store the list now (this was the *main* issue here), instead creates a file
2. Still uses GitHub Output for storing a bool
3. It's now easier to debug beacause the list is being echoed
4. The file is being removed at the end
And yeah that's about it. Will work now.
Still, it'd be much better to just grap the `checkbashisms` binary but [Debian doesn't seem to care](https://salsa.debian.org/debian/devscripts).
I waste too much time testing workflows. GitHub should make that easier somehow. (yes, it's tested)
Any additional information that reviewers should be aware of? Nope, not here.
Oopsie forgot about resolves #711
> fix(ci): `bashisms.yml`. again. will work all the time this time i swear.

- Cargo.lock
- core/Cargo.toml
- core/src/inner.rs
- tui/Cargo.toml
- tui/src/state.rs
- `tempdir` crate is not maintained and contains security vulnerabilities.
- `tempdir` depends on old version of `remove_dir_all` and is heavy weight.
- ![temp-dir](https://docs.rs/temp-dir/0.1.14/temp_dir/) an alternative to `tempdir` is light weight and is actively maintained.
- Found this security vulnerability in private linutil repo ( Not forked , used for CI testing sometimes )
- Works without issues.
- TempDir is now needed to be passed into the AppState to retain the tempdir until the end of the program.
> security patch: temp-dir

- .github/workflows/typos.yml
- _typos.toml
This uses [typos](https://github.com/crate-ci/typos).
I first wanted it to check only changed files but I've decided not to do that because
- now it can be ran on push & workflow dispatch
- the action didn't work with a list of files for some reason
Works as expected.
This will fail if there are **any** typos on the **whole** branch.
> ✅ ci: add a spellcheck typos CI

- .github/workflows/shellcheck.yml
- core/tabs/applications-setup/Developer-tools/sublime-setup.sh
- core/tabs/system-setup/arch/server-setup.sh
- start.sh
Tabs are problematic when rendering previews of shell scripts, as it results in a disparity between the position of expected rendered characters and where they may actually be rendered on the screen, and having mixed space/tab indentation in the same file is generally problematic as well.
- Emit all errors found within the changed files using gh actions toolkit annotations, before, the workflow would fail on the first shellcheck invocation that had an error emission
- Add a tab indentation check to enforce consistency in code style
- removed all current tab indentations that I've found in shell scripts
Verified using workflow runs within my own repository
Helps provide complete error information from both shellcheck and tab indentation detection
> Emit all shellcheck errors using github action toolkit annotations and check for tab indentation

- core/tabs/system-setup/compile-setup.sh
- core/tabs/system-setup/gaming-setup.sh
- Remove unnecessary quotes around packages variable in compile-setup and gaming-setup.
- Tested on arch linux works, no issues.
- Resolves #690 
- Resolves #688
> fix: Remove quotes for packages

- core/tabs/utils/tab_data.toml
missing set resolution script from tab-data.toml + refactoring
> missing script in toml file + refactoring - Monitor Control 

- core/tabs/system-setup/system-cleanup.sh
As you can see below, the script fails because:
1. Command structure for package removal is wrong
2. `-R` returns `1` when there are no packages provided
All fixed here
Redirecting the output to `/dev/null` so the script's output doesn't get flooded. 
Works :)
- Resolves #741
(📃 is a shell script btw)
> 📃 fix(system-cleanup): pacman orphan package removal

- core/tabs/applications-setup/zsh-setup.sh
`tee` fails if the file doesn't exist.
- Resolves #770
> 📃 fix(zsh-setup): check if `/etc/zsh/zshenv` exists

- core/tabs/utils/monitor-control/change_orientation.sh
- core/tabs/utils/monitor-control/disable_monitor.sh
- core/tabs/utils/monitor-control/enable_monitor.sh
- core/tabs/utils/monitor-control/extend_displays.sh
- core/tabs/utils/monitor-control/manage_arrangement.sh
- core/tabs/utils/monitor-control/set_primary_monitor.sh
---
---
---
---
---
I found another bug when testing this:
- Shows two separate monitors as one
- Clearly doesn't work
(📃 is a shell script btw)
> 📃 fix(monitor setup): a bug with utility-functions; newlines & colors in the scripts

- tui/src/filter.rs
- tui/src/state.rs
Added an option to abort the search with `Ctrl-C` and fixed up the shortcut tooltip a bit.
Works perfectly.
> 🦀 allow exiting out of search mode with `Ctrl-C`

- core/tabs/system-setup/system-cleanup.sh
> fix+refact(system-cleanup)

- core/tabs/utils/create-bootable-usb.sh
Remove inbuilt logic for finding debian & arch ISO URLs from the USB creation script. Instead, if the user selects the online ISO option, download JSON data containing the necessary information from a project I started and brought into the quickemu project, [quickget_configs](https://github.com/quickemu-project/quickget_configs). This project was created to eventually be used to fully replace functionality in the quickget bash script, similar to that present in this script. Thus, it provides the data necessary to download images of various operating systems. The data is produced daily in CI, where invalid or unresolvable URLs (and their accompanying entries) are thrown out, and other useful information, like SHA256 checksums to verify validity, are included. 
jq is used to filter through …
> feat: Drastically increase the operating system support for USB creation script

- .github/release.yml
so apparently you can't mix stuff like `labels` and `label` in YAML (f YAML)
if i try to create a release now (yes i can), it just won't generate the notes. this will fix it
> fix: github release notes not working

- core/tabs/applications-setup/waydroid-setup.sh
took some code from #797
~YOLO~ (that's a joke ofc it's tested)
- Resolves #880
> 🤖 fix(waydroid-setup): not installing `dkms` on arch

- tui/Cargo.toml
- tui/build.rs
- tui/src/state.rs
Replace `BUILD_DATE` with `CARGO_PKG_VERSION`
to make builds reproducible.
See https://reproducible-builds.org/ for why this is good.
This is an alternative solution to #869 
- Resolves #
> Replace `BUILD_DATE` with `CARGO_PKG_VERSION`

- tui/src/state.rs
regular scrolling and tab scrolling **NEEDS** to be separated, without separation, we wont be able to properly handle subdir cases
wraps the user to the top of the list or to the bottom of the list depending on where they are at
example:
https://github.com/user-attachments/assets/567753aa-7725-4cce-b83c-966a868ea207
> allow scrolling past last entry / first entry

- tui/src/filter.rs
- tui/src/state.rs
the current search functionality searches through all categories instead of just 1, so not clearing the bar when the user decides to switch categories or stops using the search bar can worsen UX because they then have to clear it manually.
https://github.com/user-attachments/assets/af8308be-f552-4933-a46f-0e31a83896b4
https://github.com/user-attachments/assets/ebece83c-ed42-419b-be18-782ae2c5ff29
> clear the search bar if the user changes categories

- core/tabs/utils/tab_data.toml
closes #773 
since fedora does not support the use of timeshift, it should be excluded.
more information is in this issue #773 
Tested using a fedora container and my main system (Arch Linux), and the precondition works flawlessly
> fix: fedora timeshift

- core/tabs/system-setup/fedora/fedora-upgrade.sh
- core/tabs/system-setup/tab_data.toml
An easy way to upgrade to the next version of fedora, not recommended (by me) for gnome and KDE spin because they support upgrades through their software store.
I have tested everything except the upgrade itself, I am currently on fedora 41 and in no mood of reinstalling my install, but the code is good so it will work.
I couldn't understand what task_list =  means in tab data, so If someone could explain what it is, I would really appreciate it
> feat(fedora): release upgrade script

- core/tabs/applications-setup/office-suites/freeoffice.sh
- core/tabs/applications-setup/office-suites/libreoffice.sh
- core/tabs/applications-setup/office-suites/onlyoffice.sh
- core/tabs/applications-setup/office-suites/wpsoffice.sh
- core/tabs/applications-setup/pdf-suites/evince.sh
- core/tabs/applications-setup/pdf-suites/okular.sh
- core/tabs/applications-setup/pdf-suites/pdfstudio.sh
- core/tabs/applications-setup/pdf-suites/pdfstudioviewer.sh
> fix: Common script paths

- .github/workflows/linutil.yml
- .github/workflows/preview.yml
- Separate preview generation from linutil release.
- Auto runs with Linutil Release workflow.
- We can trigger the preview generation for any specific release with Linutil Release workflow run id that is created after this PR.
- Run ID can be obtained from the URL of the workflow run.
- Preview commit message contains the run id which can be used to browse the files at the specific commit.
- Doesn't have a `x` in linutil.yml if the preview generation fails.
- Auto run with Linutil Release workflow https://github.com/jeevithakannan2/linutil_ci/actions/runs/11260453100
- Manual run with Linutil Release run id https://github.com/jeevithakannan2/linutil_ci/actions/runs/11260675235
> ci: Seperate preview from Linutil Release

- Cargo.lock
Cargo changes because `chrono` crate was removed in https://github.com/ChrisTitusTech/linutil/pull/878
Prevents the Cargo.lock terror
> fix: cargo.lock fixes

- Cargo.lock
- tui/Cargo.toml
> [!CAUTION]
> ~~Should not be merged before `ansi-to-tui` and `tui-term` new release~~
- **ratatui** `0.28.1` -> `0.29.0`
- **ansi-to-tui** ~~update not yet released~~ `6.0.0` -> `7.0.0`
- **tui-term** ~~update not yet released~~ `0.1.12` -> `0.2.0`
- ~~Will only work with `ansi-to-tui` and `tui-term` crates updates~~
- Works without issues.
- Closes #864
> chore: bump ratatui -> 0.29.0

- core/tabs/applications-setup/communication-apps/signal-setup.sh
- Replace repo with flatpak as it no longer exists.
- Resolves #808 
- **Depends on** #705
> fix: Signal installation in fedora

- .github/workflows/linutil.yml
- The binary name of aarch64 build was also linutil. That was the issue.
> fix: aarch64 release

- .github/workflows/bashisms.yml
- Fixed bashisms not working when manually ran.
- Trigger bashisms workflow only when sh files are changed in PRs ( Previously changes to any file inside tabs dir triggered the workflow ).
- Use [tj-actions/changed-files](https://github.com/tj-actions/changed-files) action to get the changed files in PRs.
- https://github.com/jeevithakannan2/linutil_ci/pull/8
- https://github.com/jeevithakannan2/linutil_ci/actions/runs/11262488127
> refact(ci): bashisms.yml

- .github/workflows/linutil.yml
- .github/workflows/preview.yml
- Use tags instead of runner id.
- Works
- Workflow trigger: https://github.com/jeevithakannan2/linutil_ci/actions/runs/11632985539
- Manual run: https://github.com/jeevithakannan2/linutil_ci/actions/runs/11632985539
> refact (ci): Linutil Preview use tags instead of runner id

- core/tabs/applications-setup/dwmtitus-setup.sh
After fresh Arch-Server install, using Linutil to install and configure dwm-titus, a display manager must be chosen. When choosing lightdm, a greeter is required without autologin configured. This adds the most common greeter `lightdm-gtk-greeter` to the install in case lightdm is chosen as a DM.
Tested for fresh Arch-Server install using Linutil. Boots cleanly into login screen after dwm-titus setup.
Fixes dwmtitus-setup.sh for lightdm choice
- Resolves #829 
none
> Add greeter install for lightdm during dwm-titus setup

- core/tabs/applications-setup/dwmtitus-setup.sh
I could not install dwm-titus for fresh virtual machine. On the step of selection a desktop manager i got unexpected behavior. I assumed that it was some bug with corresponding script case statement.
I reproduced it for both [debian-12-nocloud-amd64](https://cloud.debian.org/images/cloud/bookworm-backports/20241004-1890/debian-12-backports-nocloud-amd64-20241004-1890.qcow2) and [Arch-Linux-x86_64-basic](https://gitlab.archlinux.org/archlinux/arch-boxes/-/package_files/7649/download) and this successfully passed.
It is possible that there is no available package 'gdm' for debian, but this is another story.
Apparently, there is no block now to install dwm-titus from scatch on this point.
I failed to find any relate issues.
> fix (dwmtitus-setup): dm picking

- core/tabs/utils/numlock.sh
- core/tabs/utils/tab_data.toml
- docs/userguide.md
- `numlock.sh` only works in display managers and tty.
- DE have their own rule for enabling numlock on user login.
- See #777 for more information.
- Stripped comments from the script.
> docs: Change numlock description

- .github/dependabot.yml
- `stale` github action is not used in the repo
- `setup-python` github action is already above version `4` ( current version `5` )
- `crossterm` crate is already above version `0.27.0` ( current version `0.28.1` )
> Remove dependabot ignores

- tui/src/floating_text.rs
@ChrisTitusTech this pr fixes a reversion caused by https://github.com/ChrisTitusTech/linutil/pull/755
this pr reimplements the functionality added into https://github.com/ChrisTitusTech/linutil/pull/729 that stopped working due to https://github.com/ChrisTitusTech/linutil/pull/755
> fix reversion

- core/tabs/applications-setup/dwmtitus-setup.sh
When installing dwm-titus with slstatus from a fresh Arch-Server install, several required dependencies are missing and need to be included. These are:
- meson
- libev
- uthash
- libconfig
Tested only on another fresh Arch-Server install and script completed successfully.
Added required dependencies in dwm-titus install script that were failing install attempts on a fresh arch-server install. Added packages `meson libev uthash libconfig` to setupDWM function in dwmtitus-setup.sh.
Created a fresh Arch-Server install using official Arch October release and Archtitus install script from Linutil inside a VM. Booted into new install and started Linutil with modified dwmtitus-setup.sh for a dwm install. Newly added packages were installed and script completed successfully.
New Dependencies for …
> Add required dependencies for dwm-titus on Arch

- core/tabs/utils/printers/install-cups.sh
- core/tabs/utils/printers/install-epson-printer-drivers.sh
- core/tabs/utils/tab_data.toml
- docs/userguide.md
Came to mind to add this when I was struggling to get my Epson printer working earlier today on my new computer.  Turns out I forgot to install the Epson printer drivers in the AUR.  I did a search and the same package is in the Debian and Fedora repos so I added support for those, but I'm not really able to test them myself as I only use EndeavourOS.  I can comment those out in the shell script if needed.
Ran the script and verified it installed (or reinstalled in my case) the correct drivers and saw them show up in CUPS when I brought up the CUPS web interface.
Printer driver installation on Linux (and on Windows for that matter) is a real pain to get right sometimes, I'm hoping this will help people out who use Epson printers.
N/A
As I mentioned in description, I only really tested …
> feat: printer driver installation

- core/tabs/system-setup/system-update.sh
- Use `nala` after installation.
- Use `nala fetch` to get the fastest mirrors.
- Removed redundant code of updates and upgrades.
- Upgrade AUR packages also.
- Simple update logic for flatpak apps.
- The old `$PACKAGER` variable in the `printf` is actually not quoted.
- Tested on arch system and debian12 VM with no issues.
> refact: system-update.sh

- core/tabs/security/tab_data.toml
As Fedora comes with Firewalld preinstalled & preconfigured with rules set for fedora desktop out of the box. Installing ufw on it might conflict with it & is really not needed.
I have tested it
Hides firewall setup on fedora systems
> Delist Firewall setup on systems with Firewalld installed, such as fedora

- core/tabs/system-setup/fedora/multimedia-codecs.sh
Removing **multimedia** and s**ound and video** group as it no longer exist. Therefore the script results as failed and can give the wrong impression that it has failed
Tested by me 
- Resolves #803
> fix(fedora): multimedia setup

- core/tabs/utils/power-profile.sh
* Added better checking when searching /sys/class/power_supply/ directory
* Uses ls with * wildcard to find all battery entries not limited to BAT0. (e.g. BAT1, BAT2)
I have tested this on my Arch Linux install on DESKTOP. (no battery) 
However it should work.
All this does is if there is any battery it will run the function for laptops and not desktops. 
It fixes the issue of not detecting a laptop and instead runs the power profile meant for desktops.
- Resolves #871
> fix: Autocpu-freq script not detecting battery on laptops

- core/tabs/system-setup/system-cleanup.sh
When running the system cleanup option on Arch Linux (pacman), if the user has no orphaned (unused) packages the command will return 1 so the TUI think it failed and aborts. The issue is (pacman -Qtdq). So I added a check which runs it first and if the command executes sucessfully (returns 0) then it will continue with cleanup. 
I also added a output if it found any packages and if not it will let the user know it skipped. (see screenshot below)
I tested this on my Arch with pacman and it works. I also don't have any orphaned pkgs.
Without this check it will fail and not do the rest of the cleanup (logs, temp files, etc) and just aborts and skips the whole process because the control flow think it fail.
N/A
If anyone has any unused packages, check it it will detect it.
> fix(system-cleanup): failing with no orphan packages on arch

- core/tabs/applications-setup/Developer-tools/sublime-setup.sh
- core/tabs/applications-setup/browsers/brave.sh
- core/tabs/applications-setup/browsers/vivaldi.sh
- core/tabs/applications-setup/docker-setup.sh
There have been a recent syntax change in dnf5 which comes preinstalled with every distro based on fedora 41 or later, therefore I have updated all the setup scripts which requires **--add-repo** and replaced it with **addrepo --from-repofile="https://..."**. Also @jeevithakannan2 has added a version check so it doesn't conflict with systems that are not on dnf5.  
Works. Although there is an issue with upstream braves repo file, I have created an issue on their GitHub page. It will start working again once they update the upstream repo file. I think this should be merged regardless as currently no script is working with dnf5 after this 3 out of 4 will start working and after brave fixes the issue all 4 will work.
> fix(fedora): Recent syntax changes with DNF5

- core/tabs/applications-setup/waydroid-setup.sh
- Move the headers installation outside of dkms if block so that headers can be installed even if dkms is installed.
- Tested with no issues.
> refact: waydroid setup

- Cargo.lock
- core/tabs/common-script.sh
- tui/Cargo.toml
- tui/src/main.rs
- tui/src/root.rs
- tui/src/state.rs
implements a root check menu
this is a better implementation of the now closed #821
> implement a root check menu

- Cargo.lock
- Cargo.toml
- tui/Cargo.toml
- tui/src/running_command.rs
Thanks @a-kenji
Use vt100-ctt instead of patching the dep.
- Works without issues.
- Resolves #948
> Use vt100-ctt instead of patching the dep

- README.md
> docs(README): wrong crate name in `cargo install` instructions

- .github/workflows/linutil.yml
Determine the previous release by searching through the current Cargo.toml. Update necessary version fields (in Cargo.toml, as well as the linutil_core dependency in the tui's Cargo.toml), replacing the previous version with the current date. Ensure that the previous version matches the expected format to reduce the possibility of erroneous replacements.
Locally running the commands correctly modifies files with the current date.
Removes the need to manually modify the versions.
> chore: Update package version upon release action 

- core/tabs/applications-setup/tab_data.toml
- docs/userguide.md
- Remove redundant zoom entry and move zapzap from developer tools to communication.
**Before**
**After**
> Move ZapZap entry to communication apps, remove redundant zoom entry

- tui/src/floating_text.rs
- tui/src/hint.rs
- tui/src/main.rs
- tui/src/state.rs
- Fix unnecessary usage of pub mod appstate and unused float handle mouse function.
- Fix the below clippy warnings with new rust version.
```
warning: the following explicit lifetimes could be elided: 'a
--> tui/src/floating_text.rs:174:6
|
174 | impl<'a> FloatContent for FloatingText<'a> {
|      ^^                                ^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_lifetimes
= note: `#[warn(clippy::needless_lifetimes)]` on by default
help: elide the lifetimes
|
174 - impl<'a> FloatContent for FloatingText<'a> {
174 + impl FloatContent for FloatingText<'_> {
|
warning: manually reimplementing `div_ceil`
--> tui/src/hint.rs:39:16
|
39 |     let rows = (shortcut_spans.len() + columns - 1) / columns;
| …
```
> refact: minor fixes

- core/tabs/applications-setup/android-debloat.sh
- core/tabs/applications-setup/browsers/librewolf.sh
- core/tabs/applications-setup/communication-apps/discord-setup.sh
- core/tabs/applications-setup/communication-apps/signal-setup.sh
- core/tabs/applications-setup/dwmtitus-setup.sh
- core/tabs/applications-setup/linutil-installer.sh
- core/tabs/applications-setup/linutil-updater.sh
- core/tabs/system-setup/compile-setup.sh
- core/tabs/system-setup/system-cleanup.sh
- core/tabs/utils/bluetooth-control.sh
- core/tabs/utils/encrypt_decrypt_tool.sh
- core/tabs/utils/monitor-control/set_brightness.sh
- core/tabs/utils/monitor-control/set_resolutions.sh
- core/tabs/utils/ollama.sh
- core/tabs/utils/samba-ssh-setup.sh
- core/tabs/utils/service-control.sh
- core/tabs/utils/timeshift.sh
- core/tabs/utils/user-account-manager/add_to_group.sh
- core/tabs/utils/user-account-manager/change_password.sh
- core/tabs/utils/user-account-manager/delete_user.sh
- core/tabs/utils/user-account-manager/remove_from_group.sh
- core/tabs/utils/utility_functions.sh
- core/tabs/utils/wifi-control.sh
the only files i didn't fix:
- core/tabs/utils/ssh.sh (ref #996)
- core/tabs/system-setup/arch/server-setup.sh
> refact: fix (almost) all shellcheck errors

- startdev.sh
This can be resolved without changing anything by running `apk add --no-cache grep`. But we cannot ask the user to do so while we can solve this ourselves.
Tested without any issues in alpine VM
- Resolves #978
> fix(startdev): grep error

- core/tabs/applications-setup/fastfetch-setup.sh
Enhanced RC file detection in fastfetch-setup.sh by implementing a fallback mechanism to search for shell configuration files in the home directory. This improvement helps handle cases where RC files might be named differently or located in non-standard locations within $HOME.
Key changes:
- Added fallback search for .bashrc and .bash_profile in $HOME for bash
- Added fallback search for .zshrc in $HOME for zsh
- Improved error handling for cases when no RC file is found
- Tested with bash and zsh shells
- Verified fallback search works when default RC files are not present
- Confirmed proper error handling when no RC files are found
- Tested with different RC file configurations (.bashrc, .bash_profile)
- Improved reliability of shell configuration
- No new dependencies added
- Maintains …
> feat(fastfetch-setup): shell integration setup

- core/tabs/applications-setup/browsers/zen-browser.sh
This update removes the AVX2-specific logic from the installZenBrowser function. The Zen Browser team discontinued AVX2-optimized releases due to recurring build issues in GitHub workflows, so we now only install zen-browser-bin from AUR. This change streamlines the installation process.
This refactor removes the AVX2-specific logic from the `installZenBrowser` function. The Zen Browser dev team discontinued AVX2-optimized releases due to recurring build issues in GitHub workflows. As a result, the only available package on AUR is `zen-browser-bin`. This update ensures we always install `zen-browser-bin`, streamlining the process and eliminating unnecessary complexity.
- Ran the installer on a system using the `paru` AUR helper and confirmed that `zen-browser-bin` installs as expected.
- …
> fix(zen-browser): remove redundant AVX2 check

- tui/src/main.rs
- tui/src/running_command.rs
This small PR, makes, so that the UI is not re-rendered, unless an event is detected. The event might be a terminal event (keypress, mouse moved, resize, etc.)
Or if a terminal is open, if some new input came in from the terminal
Before: 50% CPU usage on my machine with debug on
After: 1% CPU usage on my machine with debug on
It doesn't impact the performance of the app, it will run just as fast as before, but it affects it's efficiency, so it's not re-rendered unless it should be.
I am not aware of any possible side effects this might create, but if in the future we want to implement something like an animation system, it will complicate it a little.
> perf: increase rendering efficiency

- core/tabs/system-setup/compile-setup.sh
Fixes Build Prerequistes for Fedora and RHEL. Uses powertools for older rhel or rocky and crb for new builds. Also development tools work with dnf 4 or 5.
Tested on Fedora 39, 41 and Rocky 9. 
- Resolves #1001
> fix(compile-setup): dnf compile 

- core/tabs/applications-setup/dwmtitus-setup.sh
Added picom depends for apt, dnf, and zypper. Added Zypper, and Alpine for install. Slight change in dm check. 
Tested in Arch, Fedora 41, Debian, Opensuse Tumbleweed, Alpine
- Resolves #1005 
I know Chris may be picky about touching dwmtitus...
> fix(dwm-titus): Multiple fixes

- core/tabs/system-setup/remove-snaps.sh
Nala doesn't like autoremove. Replaced with remove. Works with both apt-get and nala. 
Tested in Xubuntu
- Resolves #1037
> fix(remove-snaps): snapd uninstallation

- core/tabs/system-setup/arch/server-setup.sh
Add --score 5 to return mirrors that have score less than 5 making sure that most of the returned mirrors are active
- Resolves #1035
> fix: reflector returning mirrors that are down

- core/tabs/utils/samba-ssh-setup.sh
The SSH-Samba script forgets to import the common-service-script so it fails trying to enable the sshd or samba service.
When it tries to call StartandEnableService it can't find it since it's not imported, so I just added the import.
I have tested my code and its gets through the ssh part however there is a unrelated error for samba in the input handling, once I find a fix for that I will create a separate pr.
No impact just fixes an error.
None
Not right now
> fix(ssh-samba): Missing import of common service script

- core/tabs/system-setup/compile-setup.sh
Fixes build essentials install for debian based system. Shellcheck (quotes) was causing errors. 
Debian, Ubuntu
Double quotes were messing up most of the builds on the script. I disabled [shellcheck](https://www.shellcheck.net/wiki/SC2086)
- Resolves #1065
> fix builds essentials for debian based systems

- core/tabs/system-setup/arch/paru-setup.sh
- core/tabs/system-setup/arch/yay-setup.sh
Fixes yay installation along with paru when running paru installation.
Setting `AUR_HELPER_CHECKED=true` when running paru or yay installation scripts makes sure the installation of yay doesn't happen which is defined in the common-script checkAURHelper function
- Resolves https://github.com/ChrisTitusTech/linutil/issues/1051
> fix: yay installing along paru

- core/tabs/utils/printers/install-hp-printer-drivers.sh
- core/tabs/utils/tab_data.toml
- docs/userguide.md
Added an install HP printer drivers script to facilitate the install of `hplip` on various linux systems which support it.
Tested on debian 12 system with `hplip` uninstalled and use `linutil` to install the package for us
[linutil_install_hp_printer_drivers.log](https://github.com/user-attachments/files/20961571/linutil_install_hp_printer_drivers.log)
[linutil_already_installed.log](https://github.com/user-attachments/files/20961583/linutil_already_installed.log)
Allows any user to install `hplip` printer drivers if cups is not enough for printing on their HP Printer.
See [here](https://www.openprinting.org/printers/manufacturer/HP) for supported printers. However in tests my printer a HP Deskjet 2700 series was able to print without it, so might not be exhaustive list or my printer …
> Added script Install HP Printer Drivers in utils/printers

- core/tabs/system-setup/fedora/rpm-fusion-setup.sh
Fixes RPM fusion and asks to install tainted RPM fusion installs. 
Fedora 42 and Fedora 40 (even though it's now EOL)
Fixes Fedora 41 and greater logic as well as asks to add tainted repos due to dubious legality. 
- Resolves #1084 
Latest commit e5a32fe doesn't include Fedora 41 and greater dnf5 logic.
> fix(rpm-fusion): Fixes Fedora 41 logic for RPM fusion for latest commit. 

- .github/workflows/bashisms.yml
- .github/workflows/issue-slash-commands.yaml
- .github/workflows/rust.yml
- .github/workflows/typos.yml
- fix potential code injection in `issue-slash-commands.yaml` by using
single quotes insted of double, see
https://www.gnu.org/software/bash/manual/html_node/Double-Quotes.html
- declare permissions for all workflows, see
https://codeql.github.com/codeql-query-help/actions/actions-missing-workflow-permissions
> fix(ci): various security vulnerabilities

- core/tabs/system-setup/gaming-setup.sh
Exact Error message is: "Unable to handle repository shortcut 'contrib':
this happens when running the line manually as well
The below line breaks on Ubuntu and some of its forks (Only tested about 4)
"$ESCALATION_TOOL" apt-add-repository contrib -y
Preformed unit testing on the script on Debian, Ubuntu, Kubuntu, Xubuntu
This will fix Ubuntu users trying to run the Gaming Dependencies.  Provide an updated install of Steam for Debian users
- Resolves #1101
move software-properties-common to the DISTRO_DEPS
The below line does not seem to be needed in Debian, NOTE: only tested Debian, Ubuntu and some Ubuntu forks.
"$ESCALATION_TOOL" apt-add-repository contrib -y
The below can also be changed as Debian has a later version of Steam in apt now. Remove the IF statement. The line in the ELSE …
> [Bug]: Debian/Ubuntu gaming setup

- core/tabs/system-setup/arch/chaotic-aur-setup.sh
- core/tabs/system-setup/tab_data.toml
- docs/userguide.md
I added support for the installation of the Chaotic-AUR repo for Arch systems. I added a new script that installs and configures the Chaotic-AUR repo.  I also updated the corresponding tab data. This aims to solve #1115 
I was not able to test the change in linutil due to me not having an Arch system and running on a ARM64 machine, but linutil compiled withouy any errors and ran like it should. If anyone can test my changes, that would be great.
The change impacts the user experience by making the install of the Chaotic-AUR quick and easy. No performace hit measured. No new dependencies were added.
- Resolves #1115 
This is AI-generated code! I know it's against the contributors guidelines, but the code looks correct to me. To be sure that the code works, please review this PR very …
> Feat: Add support for installation of Chaotic-AUR in Linutil
