README.md
Fixes the spelling mistakes and restructures the documentation
=> documentation fixes

src/list.rs
This pull request contains the functionality of previewing an actions content.
This can be done by pressing the 'p' key while hovering an item.
I tried to adhere to the projects structure when adding this feature.
If there are any concerns, please tell me so I can try to fix them :)
=> Add action preview functionality

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE.md
Adds multiple templates to LinUtil
=> Adds templates to LinUtil

src/commands/system-setup/2-gaming-setup.sh
=> Fix Steam on Debian. Closes Issue 49

.github/workflows/github-pages.yml
Create github-pages.yml
Create github-pages.yml for docs
Fully tested in WinUtil
Full to help users
[What issue/discussion is related to this PR (if any)]
- Resolves no issues
Nope
=> Create github-pages.yml for docs

src/commands/system-update.sh
Attempt to reduce headache with archlinux-keyring
Prevent issues with pacman when archlinux-keyring is out of date
woks
none
=> Attempt to reduce headache with archlinux-keyring

README.md
Just add a ":" before the command for better look
=> Add a colon to the docs for better look

README.md
Update README.md to add docs URL
Update README.md to add docs URL
None required
High as helps new users
[What issue/discussion is related to this PR (if any)]
- Resolves no issues
[Any additional information that reviewers should be aware of.]
=> Update README.md to add docs URL

src/commands/system-update.sh
Update flatpaks in system-update
Run flatpak update -y if flatpak is installed on the system. 
- Resolves #114
=> feat: Update flatpaks in system-update

README.md
✨ This PR reduces the overabundance of commas and periods to make the documentation look more professional ✨
=> Reduce redundant commas and structure the md better

src/commands/applications-setup/dwmtitus-setup.sh, src/list.rs
Finally fixed DWM-Titus and works with the new UI
=> DWM-Titus fixed and ready

src/commands/security/firewall-baselines.sh
[Provide a succinct and descriptive title for the pull request.]
Refactor firewall-baselines.sh script and fix bugs that make it not work
Tested it in multiple scenarios (ufw installed or not, ubuntu, arch)
Made the script work
[What issue/discussion is related to this PR (if any)]
- Resolves #
[Any additional information that reviewers should be aware of.]
=> Fix ufw firewall script

docs/updates.md, mkdocs.yml
heya, my first PR over here..
Based on your request for winutil I also removed changelog (here updates) from the documentation.
=> remove updates (changelog)

src/commands/utils/bluetooth-control.sh, src/commands/utils/wifi-control.sh
=> Resolves #164

src/commands/system-setup/arch/server-setup.sh, src/commands/system-setup/tab_data.toml
We are about to make the fastest arch install known to man!
ArchTitus
Setup arch, blazingly fast, minimal, and simply the best.
People test stuff?
Hopefully it doesn't blow up my system
There will be many after this gets merged
- Resolves Nothing
Taking the best of ArchTitus and bringing it into 2024
=> ArchTitus Implementation

src/commands/system-setup/arch/server-setup.sh
=> fix archtitus

src/commands/system-setup/1-compile-setup.sh, src/commands/system-setup/3-global-theme.sh
Removes unnecessary cloning functionality
- Resolves #161 
- Resolves #122
=> Remove unnecessary cloning functionality

README.md
=> Add dev branch to readme.md

src/commands/applications-setup/alacritty-setup.sh, src/commands/applications-setup/dwmtitus-setup.sh, src/commands/applications-setup/kitty-setup.sh, src/commands/applications-setup/rofi-setup.sh, src/commands/applications-setup/zsh-setup.sh, src/commands/common-script.sh, src/commands/security/firewall-baselines.sh, src/commands/system-setup/1-compile-setup.sh, src/commands/system-setup/2-gaming-setup.sh, src/commands/system-setup/3-global-theme.sh, src/commands/system-setup/4-remove-snaps.sh, src/commands/system-setup/arch/paru-setup.sh, src/commands/system-setup/arch/yay-setup.sh, src/commands/system-setup/system-update.sh
Adds Multi-Escalation support so the Utility does not depend on a single Escalation-Tool, and other general improvements.
Did some testing and all of the changed scripts work perfectly
If some users are not using ``sudo`` and instead are using a different Escalation-Tool like ``doas`` then this will allow the ``doas`` users to be able to use the program without having to switch to ``sudo``
=> Add Multi-Escalation support

CONTRIBUTING.md, README.md
Finished #148, which I had forgotten to do.
=> Applied changes proposed by og-mrk in #148

src/commands/system-setup/fedora/rpm-fusion-setup.sh, src/commands/system-setup/tab_data.toml
Script to install RPM Fusion repos on Fedora
Script to install [RPM Fusion](https://rpmfusion.org/Configuration) free and non-free repositories
=> Add RPM Fusion installation script

src/commands/system-setup/fedora/rpm-fusion-setup.sh
Fixing echo that was replaced with $ESCALATION_TOOL
=> Bugfix: echo incorrectly replaced with $ESCALATION_TOOL 

src/commands/utils/numlock.sh
Change the remaining sudos to $ESCALATION_TOOL & change "main" to "numlockSetup"
Original PR for numlock #172 
Works perfectly
=> Change remaining sudos

src/commands/applications-setup/dwmtitus-setup.sh
DWM-Titus Installation Bug Fixes
Fix package names for fedora and add missing dependency for debian
Working as expected
- Closes #297
- Resolves #225 
- Resolves #296
=> fix: DWM dependecies

README.md, docs/index.md
Adds Discord
Adds Discord
None Required
None
- Resolves no issues.
Nope
=> Adds Discord

.github/mkdocs.yml
=> Fixes docs try 2 (Actually works now)

.github/CODE_OF_CONDUCT.md
Adds Code Of Conduct
Adds Code Of Conduct
None required
High as will have rules to follow with PR's
- Resolves no issues
No
=> Adds Code Of Conduct

tabs/applications-setup/dwmtitus-setup.sh, tabs/common-script.sh, tabs/security/firewall-baselines.sh, tabs/system-setup/1-compile-setup.sh, tabs/system-setup/2-gaming-setup.sh, tabs/system-setup/3-global-theme.sh, tabs/system-setup/arch/paru-setup.sh, tabs/system-setup/arch/yay-setup.sh, tabs/system-setup/fedora/rpm-fusion-setup.sh, tabs/system-setup/system-update.sh, tabs/utils/bluetooth-control.sh, tabs/utils/monitor-control/auto_detect_displays.sh, tabs/utils/monitor-control/change_orientation.sh, tabs/utils/monitor-control/disable_monitor.sh, tabs/utils/monitor-control/duplicate_displays.sh, tabs/utils/monitor-control/enable_monitor.sh, tabs/utils/monitor-control/extend_displays.sh, tabs/utils/monitor-control/manage_arrangement.sh, tabs/utils/monitor-control/reset_scaling.sh, tabs/utils/monitor-control/scale_monitor.sh, tabs/utils/monitor-control/set_primary_monitor.sh, tabs/utils/monitor-control/set_resolutions.sh, tabs/utils/monitor-control/utility_functions.sh, tabs/utils/wifi-control.sh
I replaced every bashism with posix alternatives, I removed the custom color codes that were in almost every file (utilities), I refactored a lot of stuff (utilities), and I made it rely on the common script color codes instead of the custom ones (utilities).
Tested on bash, zsh, and dash.
Rechecked every file using ``checkbashisms`` package
Greatly impacts the changed sections.
- Resolves #246 
- Resolves #147 
- Resolves #312 
- Resolves #232
- Resolves #383
- Resolves #350
- Closes #278
=> Remove every bashism

tabs/applications-setup/alacritty-setup.sh, tabs/applications-setup/kitty-setup.sh, tabs/applications-setup/rofi-setup.sh
Fixes infinite backup-creation
Fixes original config being lost to infinite backup-creation
- resolves #109
=> Fix backup functionality

tabs/applications-setup/alacritty-setup.sh, tabs/applications-setup/dwmtitus-setup.sh, tabs/applications-setup/kitty-setup.sh, tabs/applications-setup/rofi-setup.sh, tabs/gaming/diablo-ii/d2r-loot-filters.sh, tabs/system-setup/2-gaming-setup.sh
Replaces wget with curl for a more flexible approach
Works.
- Closes #298
=> Change wget to curl

tabs/applications-setup/dwmtitus-setup.sh
DWM debian fixes
- Added run time dependencies from debian12 repo https://packages.debian.org/bookworm/dwm
- Fixed a bug leading to script not executing due to package manager error
- This bug is due to checking for apt-get and not apt in the common script and using apt in the dwm script. Switching from apt to apt-get resolved the issue. 
Tested on a new debian12 install. Working as expected
- Resolves https://github.com/ChrisTitusTech/linutil/issues/420
=> fix: DWM packages and installation bug

tabs/utils/service-control.sh, tabs/utils/services/i3lock-on-lid-close.service, tabs/utils/tab_data.toml
services control script
- needs some working on add_service function. i'm not very clear on what all inputs are needed for a script to be made. it depends on what service we are creating but yeah i have made basic function. someone who's good at service management can improvise it.
- developers can add new services script into services directory. which can then be used by other users using script.
- i've added i3lock-on-lid-close as a sample script which i made for my laptop to use when lid is closed.
=> service control script added

tabs/applications-setup/alacritty-setup.sh, tabs/applications-setup/kitty-setup.sh, tabs/applications-setup/rofi-setup.sh
as of right now everything is clumped into 1 function, having separate functions for these would be much better.
Works perfectly.
Cleans up code makes everything more readable
- Resolves #408
=> Move configuration setup outside of setup functions

.github/workflows/pr-labels.yaml
- PR's that have text formatted as code crash the workflow due to it not being read as a plain text, therefore will have syntax errors.
- switch from `pull_request` to `pull_request_target` bc of limited `GITHUB_TOKEN` permission.
- other little enhancement
- tested again on own repo
- Resolves issues of workflows for pr labels
=> [CI Workflow] Fix pr-label

tabs/system-setup/6-docker-setup.sh, tabs/system-setup/tab_data.toml
cleaner docker-setup for arch, debian and rpm based distros
- closes #306  
- interactive script to install docker + docker-compose if users use yml files.
- tested on distrobox for each distro
=> docker-setup interactive script 

tabs/system-setup/arch/server-setup.sh
Increases the boot partition size.
The archwiki recommends atleast a 1 GiB size for the boot partition.
- Resolves #337
=> Increase Partition size

tabs/applications-setup/alacritty-setup.sh, tabs/applications-setup/fastfetch-setup.sh, tabs/applications-setup/kitty-setup.sh, tabs/applications-setup/mybash-setup.sh, tabs/applications-setup/neovim-setup.sh, tabs/applications-setup/rofi-setup.sh, tabs/applications-setup/zsh-setup.sh, tabs/security/firewall-baselines.sh, tabs/system-setup/system-update.sh
=> Fix grammatical errors

tabs/utils/bluetooth-control.sh
=> Remove bashisms out of bluetooth-control

tabs/utils/monitor-control/manage_arrangement.sh
=> Remove bashisms out of manage arrangement

tabs/utils/monitor-control/enable_monitor.sh
=> Remove bashism from enable monitor

tabs/applications-setup/alacritty-setup.sh, tabs/applications-setup/fastfetch-setup.sh, tabs/applications-setup/zsh-setup.sh
FIX CHRIS FAT FINGERRR
fixes missing closing bracket, fix incorrect grammar
=> Fix Chris fat finger

tabs/utils/monitor-control/change_orientation.sh
=> Remove bashisms out of change orientation

tabs/utils/monitor-control/set_primary_monitor.sh
=> Remove bashism out of set primary monitor

tabs/common-script.sh, tabs/system-setup/arch/yay-setup.sh
git to bin for faster installation
Merge #374 with this
- Resolves #413
=> git to bin for faster installation

.github/workflows/bashisms.yml
=> Crated a GitHub Workflow that checks for bashisms

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
Added a checklist that includes:
- Checking for duplicate issues and discussions
- Checking the roadmap
- (for bug_report) Checking is the issue is present on both stable and dev branches
Fixed the formatting in `feature_request.md` to match `bug_report.md`.
=> Add checklists to issue templates & fix the formatting

.github/PULL_REQUEST_TEMPLATE.md
`Documentation Update` -> `Documentation update` to match other types & the CI.
=> Fix a typo & grammar in pull request template

tabs/utils/monitor-control/disable_monitor.sh
=> Remove bashisms from disable monitor

tabs/utils/monitor-control/set_resolutions.sh
=> Remove bashisms from set resolutions

tabs/common-script.sh
=> Remove bashism in checkaurhelper function

tabs/system-setup/6-docker-setup.sh
=> Remove bashism in docker-setup

README.md
Adding AUR package version badges to `README.md`.
If you see "PACKAGE NOT FOUND", just wait 10 minutes, refresh your browser cache and it will update eventually.
- #333
=> Packages metadata update [AUR]

tabs/utils/create-bootable-usb.sh
=> Remove bashisms in create bootable usb

tabs/utils/auto-login.sh, tabs/utils/bluetooth-control.sh, tabs/utils/create-bootable-usb.sh, tabs/utils/numlock.sh, tabs/utils/ollama.sh, tabs/utils/service-control.sh, tabs/utils/timeshift.sh, tabs/utils/wifi-control.sh
=> Replace echos with printf (utils)

.github/workflows/bashisms.yml
- Changed from `apt` to `apt-get`.
- Added `apt-get update` prior to package installation, in accordance with the documentation at [GitHub Docs](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/customizing-github-hosted-runners).
- Use xargs to run checks a faster by parallel processing.
- Tested on my repo works fine.
=> enhancement: Update bashisms.yml

tabs/gaming/diablo-ii/d2r-loot-filters.sh
=> Use sh shebang and source common-script

tabs/applications-setup/dwmtitus-setup.sh, tabs/applications-setup/zsh-setup.sh
=> Replace echos with printf (applications-setup)

tabs/common-script.sh
=> Replace echos with printf (common-script)

tabs/system-setup/5-samba-ssh-setup.sh, tabs/system-setup/6-docker-setup.sh, tabs/system-setup/arch/paru-setup.sh, tabs/system-setup/arch/yay-setup.sh, tabs/system-setup/fedora/rpm-fusion-setup.sh
=> Replace echos with printf (system-setup)

tabs/gaming/diablo-ii/d2r-loot-filters.sh, tabs/security/firewall-baselines.sh
=> Replace echos with printf (gaming and security)

tabs/system-setup/fedora/nvidia-proprietary-driver-setup.sh, tabs/utils/encrypt_decrypt_tool.sh, tabs/utils/user-account-manager/add_to_group.sh, tabs/utils/user-account-manager/change_password.sh, tabs/utils/user-account-manager/delete_user.sh, tabs/utils/user-account-manager/remove_from_group.sh, tabs/utils/user-account-manager/utility_functions.sh
=> Fix bashisms

tabs/system-setup/fedora/configure-dnf.sh
=> Fix incorrectly placed quote

tabs/applications-setup/tab_data.toml
=> Flatpak description

tui/src/hint.rs, tui/src/state.rs
- Fixed description and preview hints not showing in the root directory.
- Added Caps **D** and **P** for easier access.
- Resolves #525 
Tested works as expected.
=> fix: Description and preview hints

tabs/applications-setup/browser-setup.sh
=> Adding Thorium and Librewolf to the browser script

tabs/applications-setup/browser-setup.sh
=> Fixed browser Setup

tabs/gaming/diablo-ii/d2r-loot-filters.sh
Update D2R script for SH and POSIX compatibility
Tested install and worked
Minimal
=> D2r posix update

tabs/applications-setup/tab_data.toml, tabs/system-setup/tab_data.toml, tabs/utils/tab_data.toml
Sorted all Entries Alphabetically
Works
Looks Good
=> Sorted Entries Alphabetically

tui/src/hint.rs, tui/src/state.rs
Collapsed some `if` statements so `clippy` stays calm.
=> Fixed up some Rust code formatting stuff

tabs/applications-setup/mybash-setup.sh, tabs/applications-setup/neovim-setup.sh
=> Fixed apt-get in some scripts and added nala

tui/src/state.rs
Removed an unused variable. Veeeery simple.
=> Rust formatting stuff 2 - removed an unused variable

tui/src/state.rs
Reverts ChrisTitusTech/linutil#535
=> Revert "Rust formatting stuff 2 - removed an unused variable"

tabs/applications-setup/dwmtitus-setup.sh
=> Added `unzip` installation to dwm-titus

tabs/utils/tab_data.toml
Folder on top
just works
looks good
- {x] I have performed a self-review of my own code.
=> Folders on top(as they should be)

tabs/system-setup/tab_data.toml
- Disable multi select for system setup.
=> Disable multi select for system setup

tabs/applications-setup/setup-flatpak.sh, tabs/utils/auto-login.sh, tabs/utils/bluetooth-control.sh, tabs/utils/monitor-control/set_brightness.sh, tabs/utils/ssh.sh, tabs/utils/user-account-manager/delete_user.sh, tabs/utils/wifi-control.sh
Always use read with the -r variable.
=> Fix read problems

README.md
Added crates.io badge to the README. Forgot to do this in my previous PR. Sorry.
=> Added crates.io badge to the README

.github/workflows/shellcheck.yml
The one @ChrisTitusTech (and his LLM) wrote wasn't working. This one does. I've rewritten it from scratch.
=> Fixed the spellcheck workflow

.github/workflows/bashisms.yml
=> Fix checkbashisms workflow

core/tabs/system-setup/samba-ssh-setup.sh
=> Adding "valids user" argument in share section

core/tabs/applications-setup/alacritty-setup.sh, core/tabs/applications-setup/bottles-setup.sh, core/tabs/applications-setup/fastfetch-setup.sh, core/tabs/applications-setup/kitty-setup.sh, core/tabs/applications-setup/mybash-setup.sh, core/tabs/applications-setup/neovim-setup.sh, core/tabs/applications-setup/rofi-setup.sh, core/tabs/applications-setup/zsh-setup.sh, core/tabs/security/firewall-baselines.sh
move the "installing {package}" inside of the if statements so it doesnt show if the packages already exist
=> small refactor

core/tabs/applications-setup/browser-setup.sh
Browser setup fix few potential issues.
=> Browser setup fix few potential issues. 

Cargo.lock, tui/Cargo.toml, tui/cool_tips.txt, tui/src/state.rs
Tips displays a command with its purpose of use to help us users learn new commands everytime we open the script.
Special Thanks to @adamperkowski for helping me in the rust code.
=> added tips to help users learn new commands every time :)

core/tabs/applications-setup/dwmtitus-setup.sh
add necessary packages, and fix picom cloning
as requested by Chris in the discord server.
tested
=> fix dwm titus

.github/workflows/issue-slash-commands.yaml
https://cli.github.com/manual/gh_issue_reopen
https://cli.github.com/manual/gh_issue_close
=> Allow reopening issues and closing as not planned through the CI

core/tabs/applications-setup/fastfetch-setup.sh
fix problems with fastfetch not being a package on debian 12 and only being a package on debian 13
- Resolves #570
=> fix problems with debian 12

core/tabs/applications-setup/browser-setup.sh, core/tabs/applications-setup/office-suite-setup.sh, core/tabs/system-setup/docker-setup.sh, core/tabs/system-setup/gaming-setup.sh, core/tabs/system-setup/global-theme.sh, core/tabs/system-setup/samba-ssh-setup.sh, core/tabs/utils/encrypt_decrypt_tool.sh
fix the general inconsistencies between scripts, and remove unnecessary updating.
tested
=> Fix general inconsistencies and unnecessary updating

core/tabs/applications-setup/Developer-tools/githubdesktop-setup.sh, core/tabs/applications-setup/Developer-tools/meld-setup.sh, core/tabs/applications-setup/Developer-tools/neovim-setup.sh, core/tabs/applications-setup/Developer-tools/ngrok-setup.sh, core/tabs/applications-setup/Developer-tools/sublime-setup.sh, core/tabs/applications-setup/Developer-tools/vscode-setup.sh, core/tabs/applications-setup/Developer-tools/vscodium-setup.sh, core/tabs/applications-setup/tab_data.toml
Developer essentials tool to install few most used packages by developers
=> Developer essentials

core/tabs/system-setup/arch/server-setup.sh
- Resolves #429
without refreshing the database before installing a package in the iso, it will fail due to not synchronizing package databases before hand with pacman -Sy 
this is a failsafe incase the user did not do this before curling linutil
also fixes keymapping not saving after boot
works
=> Fix archtitus issues

core/tabs/applications-setup/tab_data.toml, core/tabs/applications-setup/waydroid-setup.sh
adds waydroid, uses instructions from https://docs.waydro.id/usage/install-on-desktops for installation
tested
- Resolves #580
=> Add waydroid

core/tabs/applications-setup/Developer-tools/neovim-setup.sh
=> Add nvim version check berfore installing

core/tabs/applications-setup/tab_data.toml
fixes the capped letter in developer TOols, now its Developer tools :laughing:
=> fix capped letter

.github/workflows/bashisms.yml
=> Changed the CI to only run when `.sh` files are changed

core/tabs/system-setup/fedora/nvidia-proprietary-driver-setup.sh, core/tabs/system-setup/fedora/rpm-fusion-setup.sh, core/tabs/system-setup/fedora/virtualization.sh
Fixes some issues related to quoting and cleans up some extra unneeded commands
tested
=> Fix issues with fedora

docs/userguide.md
forgot about fedora, sorry Chris :laughing:
=> Docs update (forgot about fedora)

docs/userguide.md
- Move sub folders to H3 in user guide.
=> doc: Move sub folders to h3

.github/workflows/linutil.yml
- Fix dependencies
- Worked on linutil-fork
=> ci: Fix deps

core/tabs/applications-setup/browser-setup.sh, core/tabs/applications-setup/setup-flatpak.sh, core/tabs/common-script.sh, core/tabs/system-setup/docker-setup.sh, core/tabs/system-setup/system-update.sh
removes unnecessary packagers.
=> remove unnecessary packagers

core/tabs/applications-setup/browser-setup.sh, core/tabs/applications-setup/fastfetch-setup.sh, core/tabs/applications-setup/office-suite-setup.sh
using packager is better as apt and nala have dependency handling while dpkg does not and in which case dpkg could fail on the dep part.
=> use packager instead of dpkg

.github/workflows/issue-slash-commands.yaml
test issue and usage examples: https://github.com/adamperkowski/linutil/issues/8
above
=> ci: Add issue labeling & fix perms

.github/workflows/bashisms.yml
Don't know what's causing the issue, that's the solution for now.
=> ci: Fix `bashisms.yml`. Again.

core/tabs/system-setup/samba-ssh-setup.sh
replaces subshell with better alternative
=> replace subshell usage with alternative

core/tabs/applications-setup/tab_data.toml
adds missing task lists
tested
=> add missing task lists

tui/src/running_command.rs
- Fix directory errors when executing scripts using multi-selection.
- Works as expected.
- Resolves #622
=> Fix: multi-selection

core/tabs/system-setup/global-theme.sh
- fixes KDE' theming being bricked
- Adds actual theming for specific DE's
tested
- Resolves #165
=> fix global theming

core/tabs/utils/tab_data.toml
fixes only 1 entry being shown in monitor-control, fixes monitor-control not being at the top
tested
=> fix toml round 2

core/tabs/applications-setup/Developer-tools/vscode-setup.sh
=> Fixed VSCode AUR package

core/tabs/system-setup/gaming-setup.sh
Red Hat Already Has OpenH264 Installed And Enabled When You Update To Fedora 41
- Resolves  https://github.com/ChrisTitusTech/linutil/issues/679
Since I Do Not Use Fedora I Tested it In Box buddy Virtual Fedora Terminal
=> updating Gaming For Fedora 41

core/tabs/applications-setup/tab_data.toml, core/tabs/utils/tab_data.toml
I added descriptions to the following commands: Bottles, Auto Mount Drive, Docker Setup, and Grub Theme Setup.
As I added each description into the toml files, I build and ran the application, ensuring the description displayed as intended.
Descriptions are now available for commands that previously did not include them, which adds more context to inexperienced users.
- Improves the UI and the UX
This is my first ever pull request, as I am new to contributing to open source projects. Let me know if my added descriptions can be improved, if I can fix anything, or if I did anything incorrect in general. Thank you!
=> Add descriptions to the Applications Setup section and Auto Mount Drive

core/tabs/common-script.sh, core/tabs/system-setup/arch/paru-setup.sh, core/tabs/system-setup/arch/yay-setup.sh
=> add git as a dep

core/tabs/applications-setup/communication-apps/slack-setup.sh, core/tabs/applications-setup/communication-apps/zoom-setup.sh
The `setup-flatpak.sh` path was incorrect according to folder structure
=> fix: fixing setup flatpak script path in slack and zoom script in communication setup

core/tabs/applications-setup/Developer-tools/meld-setup.sh, core/tabs/applications-setup/tab_data.toml
=> refactor meld

core/tabs/applications-setup/Developer-tools/vscodium-setup.sh
=> remove extra space

core/tabs/applications-setup/linutil-installer.sh
uses --needed so reinstalls dont happen
tested
=> use --needed so reinstalls dont happen

core/tabs/system-setup/terminus-tty.sh
without this it would not install the fonts and go on. not good.
=> fix(terminus-tty): add an `*` packager exception

Cargo.lock
- After #693 the cargo lock was not updated leading to cargo lock issues in PR (again).
=> Update linutil cargo lock version

linutil.desktop
`linutil.desktop` is now actually useful and works.
I already bundled this desktop entry with the AUR packages ([here](https://aur.archlinux.org/cgit/aur.git/commit/?h=linutil&id=f9a8a71b0db3179652d2d8fe3f67f5e30322b1c3)). Also made it auto-assign version metadata on installation. Will update the `PKGBUILD`s as soon as this gets merged.
=> 🖥️ refact(linutil.desktop): executable paths

README.md, core/tabs/security/firewall-baselines.sh, core/tabs/system-setup/arch/server-setup.sh, core/tabs/system-setup/fedora/configure-dnf.sh, core/tabs/system-setup/fedora/nvidia-proprietary-driver-setup.sh, tui/src/state.rs
Found some typos in the project with [typos](https://github.com/crate-ci/typos). Decided to fix all of them.
I will open a PR adding a spellcheck CI. #776
=> ✏️ fix: ALL typos

.github/workflows/linutil.yml, docs/assets/preview.tape
- Refactor to use vhs github action 
- Tested on linutil fork.
- The installation of the fonts take too much time. A workaround must be done for the fonts.
=> refact: vhs github action

core/tabs/system-setup/remove-snaps.sh
- Check if snap is installed before trying to remove snap.
- Merge dnf and zypper packagers as they both have the same commands.
=> refact: remove snaps

core/tabs/applications-setup/grub-theme.sh
Backs up the (if) existing theme directory before downloading. 
Resolves #739 
(📃 is a shell script btw)
=> 📃 fix(grub-theme): theme backup

man/linutil.1, tui/Cargo.toml
As always, this will be bundled with the packages (of course).
=> 📔 docs: add a manpage

.github/workflows/xtask.yml
=> ✔️ hotfix(ci): `docs/` in the xtasks CI

.github/CONTRIBUTING.md, docs/contributing.md
=> 📖 add auto docs generation instructions to the Contributing Guidelines

.github/workflows/github-pages.yml, docs/contributing.md
Using `echo -e` to display `\n`s correctly.
- Resolves #795
=> 📖 fix(docs): newlines in `docs/contributing.md`

core/tabs/applications-setup/linutil-installer.sh
=> ⬇️ feat: desktop entry & manpage installation through `linutil-installer.sh`

.github/release.yml
Fixed up PR labeling (also deleted duplicate labels in the repo)
=> ⚙️ refact(release): better categories

.github/workflows/shellcheck.yml
- Run shellcheck on all scripts.
- Use [reviewdog/shellcheck](https://github.com/reviewdog/action-shellcheck) for shellcheck.
- Use [reviewdog/shfmt](https://github.com/reviewdog/action-shfmt) for formatting.
- See the Files Changed in the following test PRs for more info
- [Shell Formatting](https://github.com/jeevithakannan2/linutil_ci/pull/22)
- [Shell Check](https://github.com/jeevithakannan2/linutil_ci/pull/21)
=> refact(ci): ShellCheck

core/tabs/applications-setup/mybash-setup.sh
- bash-completion and fontconfig are not executables
- This PR depends on #762 
- Resolves #750
=> fix: bash deps

core/tabs/common-script.sh
closes #751 
closes #750 
allows command_exists to interpret multiple values
=> make command_exists interpret multiple values

.github/SECURITY.md
Making this default-template-ahh policy better.
=> ⚖️ docs: fix the security policy

tui/src/floating_text.rs
=> fix color bleeding

core/tabs/applications-setup/tab_data.toml
=> sort entries alphabetically

core/tabs/utils/ssh.sh
its failing because it needs to make the dir before creating a file in it
=> fix: ssh commands

core/tabs/utils/monitor-control/set_brightness.sh
testing done by Adam, since i dont have 2 monitors i could not test my self
- Resolves #714
=> fix issues with set brightness

core/tabs/system-setup/arch/paru-setup.sh
uses binary instead of building from source
=> perf(paru-setup): use `-bin` packages for faster installation

tui/src/confirmation.rs, tui/src/state.rs
https://github.com/user-attachments/assets/e7ee90e5-fa73-4823-a284-597c361d2f25
=> do not exit linutil in confirmation prompt when q is pressed

core/tabs/system-setup/system-cleanup.sh
Remove autoclean from system-cleanup.sh . Nala doesn't have autoclean command.
Please read additional information
edited the script under core/tabs/system-setup/system-cleanup.sh
saved the changes
cargo run >  System-setup > Full System Cleanup
Everything works without the error
- Resolves #
Autoclean is a command of apt-get that works. Unfortunately, nala doesn't have that command.
I tried an if statement to resolve this issue but it throws an syntax error that I couldn't resolve.
I though to make another case for nala but I leave it for discussion.
=> fix(nala): remove autoclean from `system-cleanup.sh`

core/tabs/applications-setup/docker-setup.sh
Making Docker setup to work on fedora
Working flawlessly
Life for Fedora users will be easier while installing docker
=> feat(docker-setup): fedora support

core/tabs/system-setup/arch/server-setup.sh
- Timeshift does not support labels https://github.com/linuxmint/timeshift/issues/142
- Removed partition labels from the arch server setup script.
- Timeshift working.
- Resolves #345 
- Spent over 4 hours checking out every possible reasons in a VM with crappy internet just for a simple 2 min fix 
- Lesson learnt -> Always check the known issues of the application
=> fix: btrfs issue

core/tabs/system-setup/arch/server-setup.sh
=> 🖍️ feat(arch-setup): enable colors and the easter egg in `pacman`

Cargo.lock, docs/userguide.md
i don't know what went wrong. all fixed now.
=> fix the repo

.github/workflows/shellcheck.yml, .shellcheckrc
- Add a `.shellcheckrc` for the source file.
=> fix(ci): shellcheck errors

core/tabs/utils/encrypt_decrypt_tool.sh
- Remove the unnecessary arch update.
=> fix: Unnecessary arch update

.github/workflows/linutil.yml, .github/workflows/preview.yml
- Works https://github.com/jeevithakannan2/linutil_ci/pull/27
=> refact(ci): Preview workflow to create PR

core/tabs/system-setup/gaming-setup.sh
- Added some missing deps mentioned in https://github.com/lutris/docs/blob/master/WineDependencies.md
- Tested on arch system. Works good
=> chore: Add missing gaming deps

core/tabs/common-script.sh
=> fix: flatpak path

man/linutil.1, tui/src/main.rs, tui/src/state.rs
https://github.com/user-attachments/assets/1fc37a32-2cbb-4cec-8ab7-51135672b9e5
- Resolves #919
=> 🦀 feat(ux): add a minimum size bypass cli flag

tui/src/confirmation.rs, tui/src/filter.rs, tui/src/floating_text.rs, tui/src/running_command.rs, tui/src/state.rs
adds rounded corners to the tui boxes
=> Implement Rounded corners

docs/userguide.md
=> Run xtask docgen

core/tabs/applications-setup/mybash-setup.sh
- Use escalation when running starship installing script.
- Resolves #818
=> fix: starship instllation bug when using doas

tui/src/running_command.rs
- Bump the scroll back length from `200` to `1000`.
- Works
=> Increase scroll length

README.md, start.sh, startdev.sh
- Use `linutil` arguments when using `curl`
- Works
=> Linutil arguments when using `curl`

core/tabs/utils/create-bootable-usb.sh
Fixing the confirmation prompt by converting everything to lower case and allowing yes and y as answers.
tested this and works as expected
minor
=> fix(create-bootable-usb.sh) confirmation prompt

core/tabs/applications-setup/Developer-tools/ngrok-setup.sh
- Add aarch64 version of ngrok also
- Tested on arch without issues
=> Add aarch64 support for ngrok

.github/workflows/shellcheck.yml
- Might fix permission err #911 
- I cannot reproduce this issue. So I cannot test this until this is merged.
- Closes #911
=> fix: shfmt err

README.md, man/linutil.1
- Add missing CLI options to readme.
- Sort them in alphabetical order ( Except help )
=> Update CLI arguments documentation

.github/preview.tape, .github/workflows/preview.yml
- The preview.tape file was accidentally removed with https://github.com/ChrisTitusTech/linutil/pull/888 
- Added back the `preview.tape` file
https://github.com/jeevithakannan2/linutil_ci/pull/34
=> Add accidentally deleted preview.tape

LICENSE, man/linutil.1
=> chore: update copyright year

.github/workflows/shellcheck.yml
=> remove shfmt

core/tabs/applications-setup/browsers/zen-browser.sh, core/tabs/applications-setup/tab_data.toml, docs/userguide.md
- Added [Zen](https://zen-browser.app/) browser installation script.
- Tested on arch and fedora without issues.
=> feat: Zen Browser installation

core/src/inner.rs, core/tabs/system-setup/tab_data.toml
Improve preconditions proposed by #1013. Use existing values array to remove unnecessary fields in new variants, improve naming and implementation details. Also clean up mass renaming with serde rename_all.
=> refactor: Improve File Contains precondition

core/tabs/applications-setup/browsers/brave.sh
So the folks at Brave made an[ all-in-one curl script](https://brave.com/linux/) for Linux, so just using that is better than the mess we have today.
Tested and works
=> refact(brave-install): simplify script

tui/src/state.rs
=> ui: "unselect" the current tab when in search mode

core/tabs/system-setup/compile-setup.sh
Removed tldr and trash-cli as they are not in the zypper repos. 
Tested on Tumbleweed and Leap
Fixes openSUSE build prerequistes. 
- Resolves #1000
=> fix(compile-setup): Zypper Build Prerequistes

core/tabs/applications-setup/mybash-setup.sh
Failing due to $HOME/.config dir doesn't exits
- Resolves #1094
=> fix: starship symlink failing

core/tabs/applications-setup/podman-compose-setup.sh, core/tabs/applications-setup/podman-setup.sh
Fixes syntax for adding podman and podman compose for apk, and adds support for podman in Solus. 
Also combines packagers.
=> (fix) Alpine and Solus syntax for podman

core/tabs/applications-setup/android-debloat.sh
I don't know if hotfix is the right category for an update, seemed the closest match.
Update the downloaded package.
There is an aur (and chaotic aur) package available, so the script could be updated to include that on arch.
none
1.1.1 was as big an update as 1.1.0
-
-
=> Update android debloat version to 1.1.2

core/tabs/system-setup/gaming-setup.sh
This Pr Gives ArtixLinux Gaming Support By Checking To See If The os is Artix Or Arch 
by using lib32 or multilib
Tested it On My Artix Pc And it Worked Fine
=>  Adding ArtixLinux Gaming Support

README.md
Add Discord URL
None needed
Allows people to see the Discord
- Resolves #
=> Add Discord URL

core/tabs/applications-setup/dwmtitus-setup.sh
Add NetworkManager to DWM-Titus
None. As no VM to test it.
Auto installs NetworkManager for users.
- Resolves #
=> Add NetworkManager to DWM-Titus

tui/src/float.rs, tui/src/running_command.rs
yup clippy got mad at u again for not maintaining rust code chris
should we add clippy to the release workflow? maybe that would help
=> chore(clippy): comply with new lints

.github/workflows/rust.yml, core/src/config.rs, core/src/inner.rs, core/src/lib.rs, publish.sh
🚨 THIS IS MY COMEBACK PR I CAME BACK HELLO 🚨
so basically i added unit tests for critical core functions and also some cats :3 hope its not an issue (im taking a break again if it is)
also figured would be nice to have `cargo test` in `publish.sh`
resolves #1023
=> test: implement unit tests for `linutil_core`
